lazy val root = project
  .in(file("."))
  .settings(
    name := "Fides",
    scalaVersion := "3.4.0-RC1-bin-20240109-91db06a-NIGHTLY",
    libraryDependencies += "org.scala-lang" %% "scala3-staging" % scalaVersion.value,
    libraryDependencies += "dev.zio" %% "zio" % "2.0.19",
    libraryDependencies += "dev.zio" %% "zio-streams" % "2.0.19",
    // See https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
    scalacOptions ++= Seq(
//      "-Vprofile",
//      "-Werror",
      "-Wimplausible-patterns",
      "-Wnonunit-statement",
//      "-Wunused:all",
//      "-Xdisable-assertions",
//      "-Xmax-inlines", "128",
      "-Ycheck-all-patmat",
      "-Ycheck-reentrant",
      "-Ycook-comments",
      "-Ydebug-macros",
      "-Ydebug-pos",
      "-Yexplicit-nulls",
      "-Ykind-projector:underscores",
      "-Yrequire-targetName",
      "-Ysafe-init",
      "-Ysafe-init-global",
      "-deprecation",
      "-explain",
      "-feature",
      "-language:strictEquality",
      "-new-syntax",
      "-source:future",
      "-unchecked",
    ),
    version := "0.1.0",
  )
