lazy val root = project
  .in(file("."))
  .settings(
    name := "Fides",
    // See https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/
    scalaVersion := "3.4.2-RC1",
    libraryDependencies += "dev.zio" %% "zio" % "2.0.22",
    libraryDependencies += "dev.zio" %% "zio-streams" % "2.0.22",
    libraryDependencies += "org.scala-lang" %% "scala3-staging" % scalaVersion.value,
//    libraryDependencies += "org.typelevel" %% "cats-core" % "2.10.0",
//    libraryDependencies += "org.typelevel" %% "kittens" % "3.2.0",
//    libraryDependencies += "org.typelevel" %% "shapeless3-deriving" % "3.4.0",
    // See https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
    scalacOptions ++= Seq(
//      "-Vprofile",
//      "-Werror",
      "-Wimplausible-patterns",
      "-Wnonunit-statement",
//      "-Wunused:all",
//      "-Xdisable-assertions",
//      "-Xmax-inlines", "128",
      "-Ycheck-all-patmat",
//      "-Ycheck-reentrant",
      "-Ycook-comments",
      "-Ydebug-macros",
      "-Ydebug-pos",
      "-Yexplicit-nulls",
      "-Ykind-projector:underscores",
      "-Yrequire-targetName",
      "-Ysafe-init",
      "-Ysafe-init-global",
      "-deprecation",
      "-experimental",
      "-explain",
      "-feature",
      "-language:strictEquality",
      "-new-syntax",
      "-release:21",
      "-source:future",
      "-unchecked",
    ),
    version := "0.1.0",
  )
