lazy val root = project
  .in(file("."))
  .settings(
    name := "Fides",
    // See https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/
//    scalaVersion := "3.4.2",
    scalaVersion := "3.5.0-RC1-bin-20240512-99c4c00-NIGHTLY",
    libraryDependencies += "dev.zio" %% "zio" % "2.0.22",
    libraryDependencies += "dev.zio" %% "zio-streams" % "2.0.22",
    libraryDependencies += "org.scala-lang" %% "scala3-staging" % scalaVersion.value,
//    libraryDependencies += "org.typelevel" %% "cats-core" % "2.10.0",
//    libraryDependencies += "org.typelevel" %% "kittens" % "3.2.0",
//    libraryDependencies += "org.typelevel" %% "shapeless3-deriving" % "3.4.0",
    // See https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
    scalacOptions ++= Seq(
//      "-Vprofile",
      "-Werror",
      "-Wimplausible-patterns",
      "-Wnonunit-statement",
      "-Wsafe-init",
      "-Wunused:all",
      "-Xcook-docs",
      "-Xdebug-macros",
//      "-Xdisable-assertions",
      "-Xkind-projector:underscores",
//      "-Xmax-inlines", "128",
      "-Ycheck-all-patmat",
//      "-Ycheck-reentrant",
      "-Ydebug-pos",
      "-Yexplicit-nulls",
      "-Yrequire-targetName",
      "-Ysafe-init-global",
      "-deprecation",
      "-experimental",
      "-explain",
      "-feature",
      "-language:strictEquality",
      "-new-syntax",
      "-release:21",
      "-source:future",
      "-unchecked",
    ),
    version := "0.1.0",
  )
